export default {
  "DOMAIN_URL": "/",
  "FRONT_STATIC": "/external/build/1worldonline/",
  "STATIC_ASSETS_PATH": "//d1j7k46vtbcoyo.cloudfront.net/static/",
  FRONT_STATIC_DEBUG_WIDGET: "/external/",
  FACEBOOK_ID: "928506513868392",
  URL_SERVER_API_NEW: "https://app-qa.1worldonline.biz/",
  NEW_B2C_DOMAIN: "https://ico-qa.1worldonline.biz/",
  GOOGLE_ANALYTICS_ID: "",
  ALEXA_ACCOUNT_ID: "",
  DEBUG_MODE: true,
  IS_SOURCEMAP_ENABLED: false,
  USE_MINIFIED_CSS_ONLY: false,
  UI_TRANSLATION_PATH: "external/build/1worldonline/external/languages-dist/",
  REQUIREJS_BASE: "/external/",
  i18n_PROPERTIES: {},
  ENABLE_ALEXA: false,
  FB_PAGES: "423487674365862",
  DISABLE_CACHE_DOMAIN: "1world",
  PARTNER_PREFIX: "1worldonline",
  PARTNER_NAME: "1World Online",
  PARTNER_ID: "",
  PARTNER_HEADER_ICON: "external/img/common-web/nav-menu-logo-48x26.svg",
  PARTNER_TERMS: "https://1worldonline.com/#!/terms/terms",
  PARTNER_POLICY: "https://1worldonline.com/#!/terms/privacy-policy",
  PARTNER_USE_TOKENS: true,
  PUBLIC_CONTENT_DISPLAY: true,
  SHOW_B2C: true,
  TITLE: "1World Online - Social Research Engine",
  DESCRIPTION: "We believe it's important for everyone to know what people really think about today's social issues",
  IMAGE: "external/img/icons/logo-500x500.png",
  FAVICON: "external/img/favicon-logo-32x32.ico",
  REDIRECT_FOR_VISITORS: "http://welcome.1worldonline.com/"
}